services:
  homepage-admin:
    build: .
    container_name: homepage-admin
    ports:
      - "${APP_PORT:-7099}:7099"
    volumes:
      - "${HOMEPAGE_CONFIG_PATH}:/homepage-config"
    env_file:
      - .env
    restart: unless-stopped
